const actionConstants = {
   UPDATE_FOLDERLIST: 'UPDATE_FOLDERLIST',
   PUSH_DATA_TO_SONGS: 'PUSH_DATA_TO_SONGS',
   PUSH_DATA_TO_MOVIES: 'PUSH_DATA_TO_MOVIES',
   PUSH_DATA_TO_VIDEOS: 'PUSH_DATA_TO_VIDEOS',
   PUSH_DATA_TO_ROOT: 'PUSH_DATA_TO_ROOT'
};
export default actionConstants;
